name: Using python 3.13-dev with pyenv
on: [push, pull_request]
# env:
#   VERSION: 1.24.0
#   CIBW_ARCHS_LINUX: auto
#   CIBW_ARCHS_MACOS: x86_64 arm64
#   CIBW_ARCHS_WINDOWS: AMD64
#   CIBW_TEST_SKIP: "*"
  
jobs:

  test_pyenv:
    runs-on: macos-13-arm64
    name: install pyenv
    steps:
    - name: setup pyenv
      uses: "gabrielfalcao/pyenv-action@v18"
      with:
        default: 3.10.12

    # create virtualenv for each python version

    - name: Create virtualenv for python 3.13-dev
      run: PYTHON_CONFIGURE_OPTS='--disable-gil' pyenv install 3.13-dev && pyenv global 3.13-dev

    # - name: check
    #   run: python -c 'import sysconfig; print(sysconfig.get_config_var("Py_GIL_DISABLED"))'
    - name: check
      run: python --version

    - uses: actions/checkout@v3
      with:
        repository: 'numpy/numpy'
        
    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel==2.16.2
      
    - name: Build wheels
      run: python -m cibuildwheel --output-dir wheelhouse
      # to supply options, put them in 'env', like:
      # env:
      #   CIBW_SOME_OPTION: value
    
    - uses: actions/upload-artifact@v3
      with:
        path: ./wheelhouse/*.whl
